### ISSUE TITLE
Prototype naar HTML

### ISSUE THREAD

**Issue by miel775** [miel775/the-client-website#4]
Op Figma is er een ontwerp tot stand gekomen die het idee van de website weergeeft. In het groepje met dezelfde opdrachtgever maak ik de home pagina. Dit heb ik gemaakt in groot, medium en small design.

https://www.figma.com/proto/etjtwyru0VYFTMPzBsWkSV/Bieb-in-Bloei-ontwerp?node-id=0-1&t=QrCJ5M4GD2lhborb-1

**Comment by Sidopjescherm** [comment]
Goed gebruik gemaakt van de verschillende groeperingen zoals: li, section, article en headers. Zo geef je duidelijk aan wat er wat is op de website.

Waar ik wel een vraag over had was het maken van de buttons in de navigatie balk. Want zou het niet handiger zijn om er een 'nav' van te maken en dan inplaats van buttons het 'a' linkjes te maken. Zo kan je in 1 keer werken aan al je links in de navigatie balk
