### ISSUE TITLE
html issues - Riley

### ISSUE THREAD

**Issue by ryryesther** [miel775/the-client-website#5]
ik kan je website nog niet door de validator halen omdat hij nog niet live staat doe dat altijd gelijk, veder heb je goede code probeer elk id specifiek te maken.

https://github.com/miel775/the-client-website/blob/8239d0e8e63bbee36c279f218f8664a79a60f950/index.html#L34

Bij deze link zie je dat je de aanmeld knop als id button hebt gegeven , ''sign-up'' zou bijvoorbeeld een verbetering kunnen zijn.

veder als het gaat om de elementen die je gebruikt doe je het goed , je bent al heel wat gegroeid deze aantal dagen dus ga zo door😬

**Comment by miel775** [comment]
Hij staat nu live :)
